name: terraform.yml

on: [push, pull_request] 

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
      - name: check
        run: |
         terraform init
         terraform validate
         terraform fmt -recursive 
      - name: plan
        run:  terraform plan
      - name: apply
        run: terraform apply -auto-approve  
                
